language: go
sudo: false
go:
- 1.8
- 1.6.4
- 1.7.4
install:
- go get -t ./...
before_script:
- gofmt -l -s -w ./...
- go vet ./...
- gosimple ./...
script:
- go test -i -race ./...
- go test -v -race ./...
after_script:
