language: go
sudo: false
go:
- 1.14
- 1.15
- 1.x
os:
- windows
- osx
- linux
install:
- go get -t ./...
before_script:
- gofmt -l -s -w .
- go vet ./...
script:
- go test -i -race ./...
- go test -v -race ./...
after_script:
